import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Figtree,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import AuthProvider from "@/providers/auth-provider";
import QueryProvider from "@/providers/query-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";
import { getSessionUser } from "@/lib/services";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { RedirectProvider } from "@/providers/redirect-provider";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSessionUser();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AuthProvider user={user}>
          <NuqsAdapter>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <QueryProvider>
                <RedirectProvider>
                  <TooltipProvider>{children}</TooltipProvider>
                </RedirectProvider>
                <Toaster richColors position="top-right" />
              </QueryProvider>
            </ThemeProvider>
          </NuqsAdapter>
        </AuthProvider>
      </body>
    </html>
  );
}
