import { HugeiconsIcon } from "@hugeicons/react";
import * as HugeIcons from "@hugeicons/core-free-icons";

export const Menu = (props: any) => <HugeiconsIcon icon={HugeIcons.Menu01Icon} {...props} />;
export const X = (props: any) => <HugeiconsIcon icon={HugeIcons.Cancel01Icon} {...props} />;
export const ArrowUpRight = (props: any) => <HugeiconsIcon icon={HugeIcons.ArrowUpRight01Icon} {...props} />;
export const CheckCircle2 = (props: any) => <HugeiconsIcon icon={HugeIcons.Tick01Icon} {...props} />;
export const CircleDot = (props: any) => <HugeiconsIcon icon={HugeIcons.CircleIcon} {...props} />;
export const ArrowRight = (props: any) => <HugeiconsIcon icon={HugeIcons.ArrowRight01Icon} {...props} />;
export const Bot = (props: any) => <HugeiconsIcon icon={HugeIcons.BotIcon || HugeIcons.CpuIcon} {...props} />;
export const FileText = (props: any) => <HugeiconsIcon icon={HugeIcons.DocumentCodeIcon} {...props} />;
export const CheckCircle = (props: any) => <HugeiconsIcon icon={HugeIcons.Tick01Icon} {...props} />;
export const Search = (props: any) => <HugeiconsIcon icon={HugeIcons.Search01Icon} {...props} />;
export const RefreshCw = (props: any) => <HugeiconsIcon icon={HugeIcons.RefreshIcon} {...props} />;
export const ChevronDown = (props: any) => <HugeiconsIcon icon={HugeIcons.ArrowDown01Icon} {...props} />;
export const HelpCircle = (props: any) => <HugeiconsIcon icon={HugeIcons.QuestionIcon} {...props} />;
export const Zap = (props: any) => <HugeiconsIcon icon={HugeIcons.FlashIcon} {...props} />;
export const Sparkles = (props: any) => <HugeiconsIcon icon={HugeIcons.SparklesIcon} {...props} />;
export const MessageCircle = (props: any) => <HugeiconsIcon icon={HugeIcons.Comment01Icon} {...props} />;
export const ShieldCheck = (props: any) => <HugeiconsIcon icon={HugeIcons.ShieldIcon} {...props} />;
export const Send = (props: any) => <HugeiconsIcon icon={HugeIcons.SentIcon} {...props} />;

export const Check = (props: any) => <HugeiconsIcon icon={HugeIcons.Tick01Icon} {...props} />;
export const LogIn = (props: any) => <HugeiconsIcon icon={HugeIcons.Login01Icon} {...props} />;
export const MessageSquareText = (props: any) => <HugeiconsIcon icon={HugeIcons.Comment01Icon} {...props} />;
export const GitBranch = (props: any) => <HugeiconsIcon icon={HugeIcons.CodeIcon} {...props} />;
export const Users = (props: any) => <HugeiconsIcon icon={HugeIcons.UserMultipleIcon} {...props} />;
export const UserCheck = (props: any) => <HugeiconsIcon icon={HugeIcons.UserCheck01Icon || HugeIcons.Tick01Icon} {...props} />;
export const BarChart3 = (props: any) => <HugeiconsIcon icon={HugeIcons.Chart01Icon} {...props} />;
export const Clock = (props: any) => <HugeiconsIcon icon={HugeIcons.Clock01Icon} {...props} />;
export const Smile = (props: any) => <HugeiconsIcon icon={HugeIcons.SmileIcon} {...props} />;
export const Play = (props: any) => <HugeiconsIcon icon={HugeIcons.PlayIcon} {...props} />;
export const MessageCircleHeart = (props: any) => <HugeiconsIcon icon={HugeIcons.HeartIcon || HugeIcons.Comment01Icon} {...props} />;
export const Info = (props: any) => <HugeiconsIcon icon={HugeIcons.InformationCircleIcon} {...props} />;
export const MessageSquare = (props: any) => <HugeiconsIcon icon={HugeIcons.Comment01Icon} {...props} />;
export const Shield = (props: any) => <HugeiconsIcon icon={HugeIcons.Shield01Icon || HugeIcons.ShieldIcon} {...props} />;
export const Mail = (props: any) => <HugeiconsIcon icon={HugeIcons.Mail01Icon} {...props} />;
export const Globe = (props: any) => <HugeiconsIcon icon={HugeIcons.Globe02Icon} {...props} />;
export const MapPin = (props: any) => <HugeiconsIcon icon={HugeIcons.Location01Icon} {...props} />;
